/**
 * Unipile API client (server-only).
 *
 * DSN and API key come from env:
 *   UNIPILE_DSN        e.g. https://api17.unipile.com:14700
 *   UNIPILE_API_KEY    the X-API-KEY token
 *   UNIPILE_WEBHOOK_SECRET  HMAC shared secret (generated by us)
 *
 * Docs: https://developer.unipile.com
 */

const UNIPILE_DSN = process.env.UNIPILE_DSN ?? "";
const UNIPILE_API_KEY = process.env.UNIPILE_API_KEY ?? "";

function assertConfigured() {
  if (!UNIPILE_DSN || !UNIPILE_API_KEY) {
    throw new Error(
      "Unipile is not configured. Set UNIPILE_DSN and UNIPILE_API_KEY.",
    );
  }
}

type FetchOptions = {
  method?: "GET" | "POST" | "PATCH" | "DELETE" | "PUT";
  query?: Record<string, string | number | boolean | undefined>;
  body?: unknown;
  // Unipile send endpoints take multipart/form-data, not JSON.
  form?: FormData;
  signal?: AbortSignal;
};

async function unipileFetch<T>(path: string, opts: FetchOptions = {}): Promise<T> {
  assertConfigured();

  const url = new URL(`/api/v1${path}`, UNIPILE_DSN);
  if (opts.query) {
    for (const [k, v] of Object.entries(opts.query)) {
      if (v !== undefined && v !== null) url.searchParams.set(k, String(v));
    }
  }

  const headers: Record<string, string> = {
    "X-API-KEY": UNIPILE_API_KEY,
    accept: "application/json",
  };

  let body: BodyInit | undefined;
  if (opts.form) {
    body = opts.form;
  } else if (opts.body !== undefined) {
    body = JSON.stringify(opts.body);
    headers["content-type"] = "application/json";
  }

  const res = await fetch(url.toString(), {
    method: opts.method ?? (body ? "POST" : "GET"),
    headers,
    body,
    signal: opts.signal,
    // Server-only, never cache.
    cache: "no-store",
  });

  const text = await res.text();
  const json = text ? safeJson(text) : null;

  if (!res.ok) {
    const fromJson =
      json && typeof json === "object" && "message" in json
        ? String((json as { message: unknown }).message)
        : null;
    const msg = fromJson ?? `Unipile ${res.status} ${res.statusText}`;
    throw new UnipileError(msg, res.status, json);
  }

  return json as T;
}

function safeJson(text: string): unknown {
  try { return JSON.parse(text); } catch { return text; }
}

export class UnipileError extends Error {
  status: number;
  payload: unknown;
  constructor(message: string, status: number, payload: unknown) {
    super(message);
    this.status = status;
    this.payload = payload;
  }
}

// ---------------------------------------------------------------------------
// Accounts
// ---------------------------------------------------------------------------

export type UnipileAccount = {
  id: string;
  type: string;               // 'GOOGLE' | 'OUTLOOK' | 'MAIL' ...
  name?: string;
  sources?: Array<{ id: string; status: string }>;
  connection_params?: Record<string, unknown> | null;
  created_at?: string;
};

export async function listAccounts(): Promise<UnipileAccount[]> {
  const res = await unipileFetch<{ items: UnipileAccount[] }>("/accounts");
  return res.items ?? [];
}

export async function getAccount(id: string): Promise<UnipileAccount> {
  return unipileFetch<UnipileAccount>(`/accounts/${id}`);
}

export async function deleteAccount(id: string): Promise<void> {
  await unipileFetch<void>(`/accounts/${id}`, { method: "DELETE" });
}

// ---------------------------------------------------------------------------
// Hosted auth (user-facing OAuth link)
// ---------------------------------------------------------------------------

export type HostedAuthRequest = {
  type: "create";
  providers: "GOOGLE" | "OUTLOOK" | "MAIL" | "*";
  api_url: string;            // our DSN (what Unipile calls back to)
  expiresOn: string;          // ISO datetime
  notify_url?: string;        // our webhook url (optional)
  name?: string;              // correlation id for success callback
  success_redirect_url?: string;
  failure_redirect_url?: string;
};

export type HostedAuthResponse = {
  url: string;
  object: string;
};

export async function createHostedAuthLink(
  req: HostedAuthRequest,
): Promise<HostedAuthResponse> {
  return unipileFetch<HostedAuthResponse>("/hosted/accounts/link", {
    method: "POST",
    body: req,
  });
}

// ---------------------------------------------------------------------------
// Mail: list / get / send
// ---------------------------------------------------------------------------

export type UnipileMailAddress = {
  display_name?: string | null;
  identifier?: string | null; // email
};

export type UnipileMail = {
  id: string;
  account_id: string;
  provider_id?: string;
  message_id?: string;               // RFC822 Message-Id header
  thread_id?: string;
  in_reply_to?: string | null;
  references?: string[] | null;
  subject?: string | null;
  body?: string | null;              // html
  body_plain?: string | null;
  from_attendee?: UnipileMailAddress | null;
  to_attendees?: UnipileMailAddress[] | null;
  cc_attendees?: UnipileMailAddress[] | null;
  bcc_attendees?: UnipileMailAddress[] | null;
  date?: string;                     // ISO
  folder?: string;                   // 'INBOX' | 'SENT' | ...
  is_read?: boolean;
  has_attachments?: boolean;
  attachments?: Array<{ id: string; name: string; mime?: string; size?: number }> | null;
};

export type ListMailsOptions = {
  account_id: string;
  limit?: number;                    // max 250
  cursor?: string;
  before?: string;                   // ISO
  after?: string;                    // ISO
  folder?: string;                   // 'INBOX' | 'SENT' | 'ALL'
  role?: "inbox" | "sent" | "draft" | "trash";
};

export async function listMails(
  opts: ListMailsOptions,
): Promise<{ items: UnipileMail[]; cursor?: string }> {
  return unipileFetch<{ items: UnipileMail[]; cursor?: string }>("/emails", {
    query: {
      account_id: opts.account_id,
      limit: opts.limit ?? 100,
      cursor: opts.cursor,
      before: opts.before,
      after: opts.after,
      folder: opts.folder,
      role: opts.role,
    },
  });
}

export async function getMail(id: string): Promise<UnipileMail> {
  return unipileFetch<UnipileMail>(`/emails/${id}`);
}

export type SendMailRequest = {
  account_id: string;
  to: Array<{ display_name?: string; identifier: string }>;
  cc?: Array<{ display_name?: string; identifier: string }>;
  bcc?: Array<{ display_name?: string; identifier: string }>;
  subject: string;
  body: string;                      // html
  reply_to?: string;                 // provider message id to reply to
  tracking_options?: {
    opens?: boolean;
    links?: boolean;
  };
};

export async function sendMail(
  req: SendMailRequest,
): Promise<{ id: string; provider_id?: string; tracking_id?: string }> {
  return unipileFetch("/emails", { method: "POST", body: req });
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function providerFromUnipileType(type: string | undefined): string {
  switch ((type ?? "").toUpperCase()) {
    case "GOOGLE":
    case "GMAIL":
      return "gmail";
    case "OUTLOOK":
    case "MICROSOFT":
      return "outlook";
    case "MAIL":
    case "IMAP":
      return "imap";
    default:
      return (type ?? "unknown").toLowerCase();
  }
}
